In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.metrics import mean_squared_error

In [2]:
wage_dataset =np.array( pd.read_csv('Problem_3/Wage_dataset.csv', header=None))
train = wage_dataset[0:2400]
test = wage_dataset[2400:3000]
test

array([[2.00800000e+03, 4.00000000e+01, 2.00000000e+00, ...,
        1.00000000e+00, 4.50514998e+00, 9.04819134e+01],
       [2.00600000e+03, 5.60000000e+01, 2.00000000e+00, ...,
        1.00000000e+00, 4.76342799e+00, 1.17146817e+02],
       [2.00900000e+03, 5.00000000e+01, 2.00000000e+00, ...,
        1.00000000e+00, 4.60205999e+00, 9.96894637e+01],
       ...,
       [2.00500000e+03, 2.70000000e+01, 2.00000000e+00, ...,
        2.00000000e+00, 4.19312460e+00, 6.62294083e+01],
       [2.00500000e+03, 2.70000000e+01, 1.00000000e+00, ...,
        1.00000000e+00, 4.47712125e+00, 8.79810328e+01],
       [2.00900000e+03, 5.50000000e+01, 5.00000000e+00, ...,
        1.00000000e+00, 4.50514998e+00, 9.04819134e+01]])

In [3]:
def D(x,k):
    D1=[]
    for i in range(len(x)):
        a=[]
        for j in range(k+1):
            a.append(x[i]**j)
        D1.append(a)
    return D1

In [4]:
def poly_regression(D,R):
    w = np.linalg.inv(np.transpose(D)*D)*np.transpose(D)*np.transpose(R)
    return w

In [5]:
wage = train[10]
wage

array([2.00700000e+03, 4.50000000e+01, 4.00000000e+00, 1.00000000e+00,
       3.00000000e+00, 2.00000000e+00, 2.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 4.76342799e+00, 1.17146817e+02])

In [9]:
Age = train[1]
r = np.matrix(Age)
D_matrix = np.matrix(D(Age,4))

In [10]:
w_train = poly_regression(D_matrix, r)

In [12]:
Age_test = test[1]
r_test = np.matrix(Age_test)
D_matrix_test = np.matrix(D(Age_test,4))
D_matrix_test

matrix([[1.00000000e+00, 2.00600000e+03, 4.02403600e+06, 8.07221622e+09,
         1.61928657e+13],
        [1.00000000e+00, 5.60000000e+01, 3.13600000e+03, 1.75616000e+05,
         9.83449600e+06],
        [1.00000000e+00, 2.00000000e+00, 4.00000000e+00, 8.00000000e+00,
         1.60000000e+01],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
         1.00000000e+00],
        [1.00000000e+00, 5.00000000e+00, 2.50000000e+01, 1.25000000e+02,
         6.25000000e+02],
        [1.00000000e+00, 2.00000000e+00, 4.00000000e+00, 8.00000000e+00,
         1.60000000e+01],
        [1.00000000e+00, 2.00000000e+00, 4.00000000e+00, 8.00000000e+00,
         1.60000000e+01],
        [1.00000000e+00, 2.00000000e+00, 4.00000000e+00, 8.00000000e+00,
         1.60000000e+01],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
         1.00000000e+00],
        [1.00000000e+00, 4.76342799e+00, 2.26902463e+01, 1.08083354e+02,
         5.14847275e+02],
        [1

In [16]:
predicted = D_matrix_test*w_train

test.shape

(600, 11)

In [20]:
mean_squared_error(predicted,test[10])

64.91911208641828

In [24]:
Year = train[0]
Year_matrix = np.matrix(Year)
D_matrix_year = np.matrix(D(Year,4))
w_train_year = poly_regression(D_matrix_year, Year_matrix)
Year_test = test[0]
Year_test_matrix = np.matrix(Year_test)
D_matrix_test = np.matrix(D(Year_test,4))
predicted_year = D_matrix_test*w_train_year
mean_squared_error(predicted_year,test[10])

81.91227514103052

In [ ]:
wage_dataset.plot(x=10, y=5, style=['o'])