In [220]:
from sklearn.metrics import confusion_matrix

In [180]:
import csv
import random
import math
import numpy as np
from scipy.stats import multivariate_normal
from sklearn.metrics import confusion_matrix


train=csv.reader(open('P1_data/P1_data_train.csv'))
train_data=[]
for r in train:
    train_data.append(r)
train_data=np.array(train_data).astype(np.float32)

    
test=csv.reader(open('P1_data/P1_data_test.csv'))
test_data=[]
for r in test:
    test_data.append(r)
test_data=np.array(test_data).astype(np.float32)
    
    
trainfile=csv.reader(open('P1_data/P1_labels_test.csv'))
test_label=[]
for r in trainfile:
    test_label.append(r[0])
test_label=np.array(test_label)

    
trainfile=csv.reader(open('P1_data/P1_labels_train.csv'))
train_label=[]
for r in trainfile:
    train_label.append(r[0])
train_label=np.array(train_label)


index_5=[]
index_6=[]

        
index_5=[i for i in range(len(train_label)) if train_label[i]=='5']

index_6=[i for i in range(len(train_label)) if train_label[i]=='6']

data_5= [train_data[i] for i in index_5 ]
data_5=np.array(data_5)

data_6= [train_data[i] for i in index_6 ]
data_6=np.array(data_6)

mean_5=np.mean(data_5 , axis= 0)
mean_6=np.mean(data_5 , axis= 0)


nominator=np.dot((data_5[: ,: ]-mean_5.T).T ,data_5[: ,: ]-mean_5.T ) 
std =np.sqrt(np.mean(nominator , axis=0)*64/63)




cov_5= np.cov(data_5.T )
cov_6=np.cov(data_6.T)

cov_5.shape




(64, 64)

In [185]:
mean_5

array([ 5.       ,  5.0833335,  8.515152 , 10.340909 , 10.772727 ,
        9.588384 ,  6.3560605,  4.767677 ,  5.229798 ,  6.209596 ,
       10.785354 , 10.085858 ,  8.828282 ,  7.9116163,  5.6237373,
        4.699495 ,  4.790404 ,  6.823232 , 10.239899 ,  7.20202  ,
        6.0555553,  5.04798  ,  4.757576 ,  4.6868687,  5.0757575,
        6.628788 , 10.510101 ,  9.997475 ,  7.9974747,  6.537879 ,
        4.8131313,  4.712121 ,  5.1868687,  5.719697 ,  7.6010103,
        8.186869 ,  8.886364 ,  7.9116163,  5.7777777,  4.4343433,
        4.823232 ,  5.159091 ,  5.3434343,  6.0631313,  7.699495 ,
        8.724748 ,  6.1666665,  4.8156567,  4.568182 ,  5.1136365,
        7.239899 ,  8.017676 ,  9.159091 ,  8.128788 ,  5.8131313,
        4.866162 ,  4.737374 ,  5.1262627,  8.964646 , 10.563131 ,
        9.065657 ,  6.739899 ,  5.068182 ,  5.2449493], dtype=float32)

In [186]:
mean_6

array([ 5.       ,  5.0833335,  8.515152 , 10.340909 , 10.772727 ,
        9.588384 ,  6.3560605,  4.767677 ,  5.229798 ,  6.209596 ,
       10.785354 , 10.085858 ,  8.828282 ,  7.9116163,  5.6237373,
        4.699495 ,  4.790404 ,  6.823232 , 10.239899 ,  7.20202  ,
        6.0555553,  5.04798  ,  4.757576 ,  4.6868687,  5.0757575,
        6.628788 , 10.510101 ,  9.997475 ,  7.9974747,  6.537879 ,
        4.8131313,  4.712121 ,  5.1868687,  5.719697 ,  7.6010103,
        8.186869 ,  8.886364 ,  7.9116163,  5.7777777,  4.4343433,
        4.823232 ,  5.159091 ,  5.3434343,  6.0631313,  7.699495 ,
        8.724748 ,  6.1666665,  4.8156567,  4.568182 ,  5.1136365,
        7.239899 ,  8.017676 ,  9.159091 ,  8.128788 ,  5.8131313,
        4.866162 ,  4.737374 ,  5.1262627,  8.964646 , 10.563131 ,
        9.065657 ,  6.739899 ,  5.068182 ,  5.2449493], dtype=float32)

In [183]:
cov_5

array([[38.97721519, 21.53924051, 23.65316456, ..., 24.77468354,
        24.91392405, 25.78481013],
       [21.53924051, 38.60316456, 23.07088608, ..., 27.92299578,
        23.6221519 , 25.58966245],
       [23.65316456, 23.07088608, 44.78711162, ..., 24.03306483,
        19.3976985 , 26.96969697],
       ...,
       [24.77468354, 27.92299578, 24.03306483, ..., 45.74230277,
        26.31904488, 24.55501215],
       [24.91392405, 23.6221519 , 19.3976985 , ..., 26.31904488,
        39.38521289, 25.01616801],
       [25.78481013, 25.58966245, 26.96969697, ..., 24.55501215,
        25.01616801, 41.18794911]])

In [184]:
cov_6

array([[43.03746374, 23.49028181, 25.69353502, ..., 20.91406962,
        24.07683382, 28.56881475],
       [23.49028181, 40.40254179, 26.04896395, ..., 25.18293963,
        26.83795414, 27.82393286],
       [25.69353502, 26.04896395, 42.90302528, ..., 22.43736013,
        20.97092831, 29.23485288],
       ...,
       [20.91406962, 25.18293963, 22.43736013, ..., 40.9690565 ,
        26.76654925, 22.9340862 ],
       [24.07683382, 26.83795414, 20.97092831, ..., 26.76654925,
        46.10788783, 26.60076668],
       [28.56881475, 27.82393286, 29.23485288, ..., 22.9340862 ,
        26.60076668, 42.15437215]])

In [190]:
test_data

array([[ 4.,  3., 16., ...,  0.,  1.,  5.],
       [15.,  0., 11., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [16., 14., 16., ..., 10.,  9., 16.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0., 16., ..., 16., 15.,  8.]], dtype=float32)


y1 = multivariate_normal.pdf(data_test,mean=mean_5,cov=covariance_5)
y2 = multivariate_normal.pdf(data_test,mean=mean_6,cov=covariance_6)

In [188]:
y5 = multivariate_normal.pdf(test_data,mean=mean_5,cov=cov_5)
y6 = multivariate_normal.pdf(test_data,mean=mean_6,cov=cov_6)

In [207]:
# li=[ a  for i in range(len(test_data)) if y5[i]> ]
li = []
for i in range(len(y1)):
    if y1[i] > y2[i]:
        li.append(5)
    else:
        li.append(6)

li=np.array(li).astype(np.int32)
li

array([5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 5,
       5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6,
       6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6,
       5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 5,
       5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6,
       5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6,
       6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6,
       6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6,
       6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6,
       5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5,

In [209]:
test_label=np.array(test_label).astype(np.int32)

In [211]:
c = 0
for i in range(len(test_label)):
    if(test_label[i] == li[i]):
        c =c+ 1
c

216

In [222]:
conf_mat = confusion_matrix(test_label,li)
print(conf_mat)

[[108  47]
 [ 70 108]]


In [223]:
misclassification_error = (conf_mat[0][1]+conf_mat[1][0])/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[1][0]+conf_mat[1][1])
misclassification_error

0.35135135135135137